### ISSUE TITLE
installation instructions did not work for me

### ISSUE THREAD

**Issue by dmnkvd** [red-made/strapi-geodata#1]
I attempted to install this extension on my Strapi (v5.0.1), and did not work according to the provided config (led to build error `Error: ./src/plugins/strapi-geodata couldn't be resolved `):
```
export default () => ({
  'geodata': {
    enabled: true,
    resolve: './src/plugins/strapi-geodata'
  },
});
```
I changed it to:
```
export default () => ({
  'geodata': {
    enabled: true,
    resolve: './node_modules/strapi-geodata'
  },
});
```
Which worked to build the admin UI. However, once I was in the admin UI, clicking on the Geodata button, led to error: `The requested module '/node_modules/react-dom/index.js?v=7ff0f37e' does not provide an export named 'flushSync'`. 

I would really love to install this extension, so any support to resolve this issue would be much appreciated.

**Comment by red-made** [comment]
Hi, I tried installing the strapi-geodata plugin in a new Strapi project. It appears that after running `npm install strapi-geodata`, the plugin activates and works without requiring any additional configuration.

I’m currently using a version installed directly in the plugin folder, but only for development purposes.

To simplify the setup, try removing the configuration part. Then start in development mode or if in normal mode, make sure to build the admin panel.

I will change the README soon to reflect this information.

**Comment by red-made** [comment]
I correct myself: you need to perform a build in all cases to make the admin UI digest the new security directives (to enable the tiles).

I have updated the README; please also check strapi::security, as it has been updated (I corrected a URL).

**Comment by dmnkvd** [comment]
Thank you, I've gotten it to work! I believe my problem had to do with not using TypeScript. Really a great plugin!

**Comment by red-made** [comment]
Thanks! I’d like to implement it with a geospatial index if Strapi adds the ability to define a custom database structure. I hope that change comes in the near future.

Marking this issue as solved.

Bye!
